---
title: "Traditional Data"
format: 
  html:
    css: ../../styles.css
bibliography: ../../bibliography/ISDSE.bib
csl: ../../bibliography/elsevier-vancouver.csl
---

:::{.callout-warning}

This module is under review

:::


## Background

Data is a collection of information that can be recorded, stored, analyzed, and shared. When we think of data, we often think of things like health records, surveys, or census data which have a clear structure and is often stored electronically. However, not all forms of data fit onto a neat spreadsheet. Data can involve facts, figures, measurements, symbols, stories, and physical items. 

Indigenous data involves regalia, songs, art, language, oral traditions, cultural teachings, ceremonies, and stories which are an essential part Indigenous culture. This data is often qualitative in nature (something that cannot be numerically measured) and is often not stored electronically. 
This is contrasted with Western, post-colonial ways of working with data which are often based on machine interactions, data entry, and impersonal calculations. Indigenous data is often viewed as resilient, and some argue more resilient than anything that depends on machines or electricity (https://animikii.com/insights/decolonizing-digital-data-s-role-in-indigenous-data-sovereignty). 

To those who have never worked with Indigenous data, it may too abstract to use, particularly when most data analysts are trained to work with tidy spreadsheets of electronic, numeric data. Therefore, to share information between the Indigenous and Western worlds, we have to train people to understand and appreciate it before attempting to translate it.

> The most important thing one can do if they are working with Indigenous data is to keep an open mind. Colonialism is a deeply hegemonic force that changes the way that reality is viewed. The only way to get past this perception is to accept an unreality; something that at first glance seems absurd, abstract, or impossible. Give it enough space to grow and you may find there are voices of truth out there that have value beyond comprehension; we've just forgotten how to listen to them.(https://animikii.com/insights/decolonizing-digital-data-s-role-in-indigenous-data-sovereignty).  

Indigenous data has contributed greatly to scientific understanding


Unfortunately, Indigenous data are often fractured, incomplete, or missing due to Colonialism. 

